version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "15672:15672"  # Management UI (Web)
      - "5672:5672"    # RabbitMQ default port
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - eventbridge

networks:
  eventbridge:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
